### ISSUE TITLE
Yarn and npm can't find the package

### ISSUE THREAD

**Issue by zabavnikov** [codex-editor/embed#2]

**Comment by gohabereg** [comment]
Добрый день

Пакет был опубликован, но пока в регистре он пока не доступен. Причины нам не известны, задержка на стороне npm.

https://www.npmjs.com/package/codex.editor.embed
https://yarnpkg.com/en/package/codex.editor.embed

P.S. Мы ориентируемся не только на русско-язычную аудиторию, поэтому ваш вопрос и ответ к нему будут переведены на английский

**Comment by gohabereg** [comment]
Package is available!
https://www.npmjs.com/package/codex.editor.embed

```bash
$ yarn add -D codex.editor.embed
$ npm install --save-dev codex.editor.embed
```
